#ServiceNow Domain
domain: "https://dev119.service-now.com"

#ServiceNow User
username: "admin"

#ServiceNow Password, provide password or passwordEncrypted and encryptionKey.
password: "L527mKTYPFBG1"

passwordEncrypted:
encryptionKey:

#ServiceNow Version
serviceNowVersion: "Dublin"

#Proxy server host
proxyHost:
#Proxy server port
proxyPort:
#Proxy server user name
proxyUser:
#Proxy server password
proxyPassword:

#ServiceNow User Specific
assignmentGroup: ""
assignedTo: ""
callerId: ""
#category: ""
#location: ""