#ServiceNow Domain
domain: ""

#ServiceNow User
username: ""

#ServiceNow Password, provide password or passwordEncrypted and encryptionKey.
password: ""

passwordEncrypted:
encryptionKey:

#ServiceNow Version
serviceNowVersion: "Eureka"

#Proxy server host
proxyHost:
#Proxy server port
proxyPort:
#Proxy server user name
proxyUser:
#Proxy server password
proxyPassword:

#ServiceNow User Specific
#Please define your ServiceNow specific fields here like assignment_group, assigned_to, caller_id, category and location.
#The name should be a valid Incident table's column name.
#Do not add properties short_description, comments, impact and priority here, as they are added by the extenson automatically
fields:
   - name: "assignment_group"
     value: "Capacity Mgmt"
   - name: "assigned_to"
     value: "Don Goodliffe"
   - name: "caller_id"
     value: "abel.tuter@example.com"
   - name: "category"
     value: "request"
   - name: "location"
     value: "Denver"
   - name: "contact_type"
     value: "email"