#ServiceNow Domain
domain: "https://dev113.service-now.com"

#ServiceNow User
username: "admin"

#ServiceNow Password
password: "changeme"

#ServiceNow Version
serviceNowVersion: "Eureka"

#Proxy server host
proxyHost: ""
#Proxy server port
proxyPort: ""
#Proxy server user name
proxyUser: ""
#Proxy server password
proxyPassword: ""

#ServiceNow User Specific
assignmentGroup: ""
assignedTo: ""
callerId: ""
#category: ""
#location: ""