#ServiceNow Domain
domain: ""

#ServiceNow User
username: ""

#ServiceNow Password, provide password or passwordEncrypted and encryptionKey.
password: ""

passwordEncrypted:
encryptionKey:

#ServiceNow Version
serviceNowVersion: "Eureka"

#Proxy server host
proxyHost:
#Proxy server port
proxyPort:
#Proxy server user name
proxyUser:
#Proxy server password
proxyPassword:

#ServiceNow User Specific
assignmentGroup: ""
assignedTo: ""
callerId: ""
category: ""
#location: ""