#ServiceNow Domain
domain: ""

#ServiceNow User
username: "admin"

#ServiceNow Password, provide password or passwordEncrypted and encryptionKey.
password: ""

passwordEncrypted:
encryptionKey:

#ServiceNow Version
serviceNowVersion: "Fuji"

#Close notes text to be posted when resolving the incident
closeNotesText: "This incident is resolved"

#Proxy server URI
proxyUri:
#Proxy server user name
proxyUser:
#Proxy server password
proxyPassword:


#ServiceNow User Specific
#Please define your ServiceNow specific fields here like assignment_group, assigned_to, caller_id, category and location.
#The name should be a valid Incident table's column name.
#Do not add properties short_description, comments, impact and priority here, as they are added by the extension automatically
fields:
   - name: "assigned_to"
     value: "ITPAM_Autobot"
   - name: "category"
     value: "Inquiry / Help"
   - name: "subcategory"
     value: "Application Services"
   - name: "location"
     value: "Denver"